#!/bin/bash
#
# CKDeps - Version 6.2.2 - Analyzes Dependencies of Binary Applications Installed on Slackware
#
# Criação do Projeto: 04/04/2021
# Last update: 25/06/2023
#
# By Mauricio Ferrari. Santa Catarina, Brasil.
# Transalte into English by Locutus
###############################################################################################


# Definition of Variables

r='\e[31m'
g='\e[32m'
y='\e[33m'
b='\e[34m'
c='\e[36m'
t='\e[m'

clib='FALSE'
spkg='FALSE'
apkg='FALSE'
cpkg='FALSE'


#  Information Display

function info_view
{

printf "\n${b}CKDeps v$(grep -Eo "[0-9].[0-9]" <(head -3 $0))
Searching for Installed Packages and Searching for Missing Dependencies in Binaries.\n
${g}Syntax: $y${0##*/} $r<Parameters> \e[33margumentos\n
${g}Parameters:
\t$r-b <binary> $b:$y Searching for Dependencies in Binary Executables.
\t$r-s <packages> $b:$y Basic Search of Installed Packages on the System.
\t$r-S <packages> $b:$y Advanced Search of Installed Packages on the System.
\t$r-c <archive> $b:$y Searching for a File in the Contents of Installed Packages.\n
${g}Extra Parameters:
\t${r}i $b:$y Ignore Uppercase/Lowercase Differences.
\t    Can be used with Parameters$r s$y,${r}S$y e$r c$y.\n
${g}Usage Examples:
\t$y${0##*/} $r-b$c /usr/bin/megasync
\t$y${0##*/} $r-s$c gcc libtorrent
\t$y${0##*/} $r-Si$c qmplay2 wxgtk3
\t$y${0##*/} $r-c$c libass libXv\n\n$t"

exit 0
}


# Parameter Input

[ -t 0 ] && {
    [ ! "$1" ] && info_view || true
} || {
    set - $* $(cat -) # Redirect Support
}

arg=${*#$1}
[ -z "$arg" ] && info_view

while getopts bsSci option 2>&-; do
    case $option in
        'b') [ "$s" != "TRUE" ] && { clib=TRUE; s=TRUE; } || info_view ;;
        's') [ "$s" != "TRUE" ] && { spkg=TRUE; s=TRUE; } || info_view ;;
        'S') [ "$s" != "TRUE" ] && { apkg=TRUE; s=TRUE; } || info_view ;;
        'c') [ "$s" != "TRUE" ] && { cpkg=TRUE; s=TRUE; } || info_view ;;
        'i') parm='-i' ;;
        '?') info_view ;;
    esac
done


# Check Missing Dependencies
[ "$clib" == "TRUE" ] && {
    [ ! $(($#-1)) -eq 1 ] && {
        printf "\n${r}Too Many Parameters!$t\n\n" >&2
        exit 1
    }

    [ ! -e $arg ] && {
        printf "\n${r}Non-existent file!$t\n\n" >&2
        exit 1
    }

    ckbin=$(ldd $arg 2>&-)

    [ -z "$ckbin" ] && {
        printf "\n${r}Not a Valid Binary Executable!$t\n\n" >&2
        exit 1
    }

    cklib=$(awk -F= '{print $1}' <(grep '=> not found' <<< $ckbin))
    printf "\n${y}Missing Dependencies: $b($(wc -w <<< $cklib))$r\n$cklib$t\n\n"
    exit 0
}


#  Research Operations

cd /var/log/packages
lst=$(printf "%s\n" *)


#  Package Search

[ "$spkg" == "TRUE" ] && {
    for pkg in $arg
    {
        found=$(echo -e "$found\n$(grep $parm "$pkg" <<< $lst)")
    }
    found=$(sort -u <<< $found)
    printf "\n${y}Packages Found: $b($(wc -w <<< $found))$c$(sed "s/^/	/" <<< $found)$t\n\n"
    exit 0
}


#  Advanced Package Search
[ "$apkg" == "TRUE" ] && {
    for pkg in $arg
    {
        verify=$(grep $parm "^$pkg-[0-9]" <<< $lst)
        [ ! "$verify" ] && notfound=$(echo -e "$notfound\n\t$pkg") || found=$(echo -e "$found\n\t$verify")
    }
    printf "\n${y}Packages Found: $b($(wc -w <<< $found))$g$(sort <<< $found)$t\n"
    printf "\n${y}Packages Not Found: $b($(wc -w <<< $notfound))$r$(sort <<< $notfound)$t\n\n"
    exit 0
}


#  Package Content Search

[ "$cpkg" == "TRUE" ] && {
    for pkg in $(sort <(fmt -1 <<< $arg))
    {
        cntpkg=$(grep $parm "$pkg" <(grep -vE ':|/doc/|install/|/$' $lst))
        cntpkg=$(sed "s|:\([[:alnum:]]*[[:punct:]]*\)*||g" <<< $cntpkg)
        nmpkg=$(sed "s/^/\t/g" <(sort -u <<< $cntpkg))
        found=$(echo -e "$found\n\n$y$pkg: $b($(wc -w <<< $nmpkg)) \n$c$nmpkg$t")
    }
    printf "$(sed "1d" <<< $found)\n\n"
    exit 0
}; info_view
